#!/usr/bin/env php
<?php
declare(strict_types=1);
require_once __DIR__ . '/../bootstrap.php';

$file = isset($argv[1]) ? $argv[1] : '.env';

$file = BASEDIR . '/' . basename($file);
if (is_file($file)) {
    $config = new \vakata\config\Config();
    $config->fromFile($file);
    $data = $config->toArray();
    if (!isset($data['CONFIGFILE'])) {
        $data['CONFIGFILE'] = $file;
    }
    file_put_contents(
        BASEDIR . '/.env.php',
        '<?php' . "\n" . '// This file is autogenerated, do not edit manually!' . "\n" .
        (!$config->get('ENVCACHE', false) ? '' : '$config = ' . var_export($data, true) . ';' . "\n")
    );
    @opcache_reset();
}
